### ISSUE TITLE
Unify default and example configurations across this project

### ISSUE THREAD

**Issue by Crystal-RainSlide** [PataphysicalSociety/soupault#33]
There are at least 3 default/example configurations in this project:
1. https://soupault.app/reference-manual/#basic-configuration
2. [src/project_init.ml](https://github.com/dmbaturin/soupault/blob/master/src/project_init.ml)
3. [sample-site/soupault.conf](https://github.com/dmbaturin/soupault/blob/master/sample-site/soupault.conf
)

And they are inconsistent, with errors:

- 3 is outdated;
- the newly added `pretty_print_html` is only found in 1;
- 1 is using old `default_template` name instead of `default_template_file`;
- ...

Had better unify them and fix the errors to reduce confusion of those who can't get the ideas.

Maybe just fix them, maybe only use one single default soupault.conf file and read from it, maybe a default/example config builder to generate all those configurations from one file.

**Comment by dmbaturin** [comment]
Fair point. I've fixed the third point, but I agree the problem remains!

I think it would be possible to add a `--show-default-config` option. Since the website is built with soupault, the build process may call `soupault --show-default-config` and include it into the reference manual. I'll look into it.

I'm also thinking that the `sample-site` directory should be removed, since there's https://github.com/dmbaturin/soupault-sample-blog which provides a much more comprehensive and realistic example.

**Comment by dmbaturin** [comment]
After [this commit](https://github.com/dmbaturin/soupault-website/commit/c5fb6ac6e6aaf1284de1fd10effd3b70f9419c4d) the default config in the reference manual is auto-generated, so it will automatically stay in sync with reality.

**Comment by dmbaturin** [comment]
I fixed the sample site config yet again recently. I suppose the most acute problem was fixed by autogenerated default config and `--show-default-config` is there, but feel free to re-open if needed, of course.
