### ISSUE TITLE
rsync-friendly caching

### ISSUE THREAD

**Issue by SoniEx2** [PataphysicalSociety/soupault#41]
running soupault on 1.7GiB of HTML can take a while (like 40 minutes). it'd be nice if there was a way to cache the runs, ideally in such a way that the build dir can be rsync'd efficiently.

**Comment by egrieco** [comment]
Have you tried the `--checksum, -c` option for `rsync`?
> skip based on checksum, not mod-time & size

**Comment by SoniEx2** [comment]
yes but it makes soupault no faster.

**Comment by egrieco** [comment]
I misunderstood your issue due to the title.

One of the downsides of Soupault letting you use any program as a processor is that it can't control the side effects (files generated) as fully as more traditional SSGs. It's speed is also limited by the tools you call and not just by the executable itself (which is quite fast being written in OCaml).

I added the ability to handle [Haml](https://haml.info/) files and it drastically slowed down the build times on a small site. It went from near instant to taking a few seconds. The `haml` processor is written in Ruby, and is slow even for a Ruby program.

What are you using to process these files? Is it just `html` to `html` or are you running them through another processor?

**Comment by SoniEx2** [comment]
yeah, you'd have to tell it stuff (and make sure you're telling it the right stuff), but we think it'd be worth it.

currently just html to html, pure-soupault.

**Comment by dmbaturin** [comment]
I was thinking of basically outsourcing cache invalidation to the user. With, say, `settings.cache = true` soupault will cache everything, but the user can run `soupault --force` to invalidate the entire cache and rebuild everything.

Do you think it's a sensible approach?

**Comment by dmbaturin** [comment]
I suppose the preprocessor output caching from 4.4.0 fixes the worst bottlenecks. If you have any ideas for caching other things, please create issues for them.
