### ISSUE TITLE
[feature] recursively apply delete widgets

### ISSUE THREAD

**Issue by zzkt** [PataphysicalSociety/soupault#48]
In some cases it could be useful to repeatedly apply `delete_element` widgets to remove nested empty tags. potentially, several widgets could be run until the input and output match (i.e. no remaining matches/deletes)

e.g. with one widget that matches "em" and another that matches "span" it should be possible to remove things like `<em><span><em> </em></span></em>` or `<em><em></em></em>`

**Comment by dmbaturin** [comment]
I remember writing a reply to this issue but I have no idea why I never sent it...

The problem is that the worst case performance of such checking is exponential. Most element trees are shallow, but still. I don't think this is a good idea for a built-in option, considering that you can implement this as a plugin.

**Comment by zzkt** [comment]
I was thinking that something like `delete_all = recursive` could be useful (and would need to be set explicitly with awareness of the possible performance hit). but yes, more cosmetic than functional.

I've got a few cases where the build produces nested empty tags so will try the plugin approach.
