### ISSUE TITLE
Reference manual includes the counterfactual claim that `0` and `""` are treated as `false` in Lua 2.5

### ISSUE THREAD

**Issue by Lymia** [PataphysicalSociety/soupault#65]
Add the following lines to a plugin:

```lua
if 0 then
    print("Hello, world! with zero")
end
if "" then
    print("Hello, world! with empty string")
end
```

Observe that `0` and `""` are treated as `true`, not `false`. To the best of my knowledge, in no version of Lua, has these values ever been treated as `false`. The only values that have ever been treated as `false` are `nil` and `false` (since Lua 5.0).

Places I've found in the reference manual where this claim is made:

* https://soupault.app/reference-manual/#Table.has_key
* https://soupault.app/reference-manual/#HTML.get_attribute

**Comment by dmbaturin** [comment]
You are right! There certainly was some issue that prompted me to add that function, but what you say about the truth values of `""` and `0` is correct and my descriptions are wrong, I've removed them. 

An empty table is also true. I can't remember what the issue was, if I find it, I'll add that information to the manual.
